### ISSUE TITLE
Initial issues (continued from email)

### ISSUE THREAD

**Issue by dwmoore** [merlotsart/merlotsart#1]
This issue imports the current outstanding work to be completed on the project. Making the switch to allow better tracking and to keep all remaining tasks easily visible.

Current remaining tasks:
- ~~Private Events form page - class images (needs resize for taller aspect ratio)~~ Fixed in https://github.com/merlotsart/merlotsart/commit/33bbdd626556c99d3e6d636df4ed850cbe24535d
- ~~Private Events form page - all class names (Currently "Portrait Art", "Paint & Sip", and "Art & Mimosas")~~ Fixed in: https://github.com/merlotsart/merlotsart/commit/6f9750df0b344dc5f5ba1971faae845d97b7b5f6
- ~~Private Events form page - all class descriptions (Currently have updated copy for only "Paint & Sip")~~ Fixed in: https://github.com/merlotsart/merlotsart/commit/6f9750df0b344dc5f5ba1971faae845d97b7b5f6
- ~~Navigation - update logo image~~ Fixed in https://github.com/merlotsart/merlotsart/commit/1d7457fc53b2dbfbb1e4ddd63cd8886695bd7210

Any new issues/tasks should be opened in a new GitHub Issue.

**Comment by dwmoore** [comment]
See continuation with regards to Jr. Picasso image here: https://github.com/merlotsart/merlotsart/issues/7

**Comment by merlotsart** [comment]
Please reuse the image that is already in place for Jr. Picasso in the
staging server.
